title: Dev blog
description: Блог о программирвоании и электронике
author: Ярослав Кокорев
logo: /static/img/avatar.png
github: https://github.com/Kokorev92
about: Программист C++

baseurl: ""
url: ""

allowsearch: true

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
